import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import type React from "react";

const ubuntu = Ubuntu({
   subsets: ["latin"],
   weight: ["400", "500", "700"],
   variable: "--font-ubuntu",
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className={`${ubuntu.variable} h-full antialiased`}>
         <body className="min-h-full flex flex-col bg-linear-to-tr from-violet-800 to-purple-600">
            {children}
         </body>
      </html>
   );
}
